language:
- cpp

before_install:
  - pip install --user cpp-coveralls

dist: trusty

addons:
  sonarcloud:
   organization: "dzigen"
   token:
    secure: "ZsWGAzUdKrqw/FbmHVH3iQzh6m5J1pS9zbJjefg754BFSLFZNLGQmynRqi6DWLeY2WYTpdeBDZ1HdxPdqvDQRiLWcGjM6HxP52E8s9cfUb4tdvhvrzPZtZFN/w2aP6Km9fIC2LlbsR8ljooiL0U5KWnuHQjchWJJA6IsKLGm7p3P6R0URGv5LsWFylMoAM06kVOspt81WD+BTfXz4Z/zjyBTOrEl1LFz5IbQ8lemI19m31ub/sWL24kLlExICpIBxzS5Lj8/mAwxteaQ3lLMTUBjoX6fKRUf0Wmm0HeT92TMDWa5XVGt0BKCVeZdoqllphn9xLXuQGw6V0bcloTNnp1rYpHBP4W7EHeWl+LHMflkFuYNL2YK/00WxQqBGk7kXeRBwuvJUkqNODMWGiTcIefqSdrzACE+wED4LeppAhF/Hq2/+ba9PcbmG6D81NurbUUvh+VKIHBAFEQdBSaG7u3cpRVHVfOBHzIYMxg8QX40CcMotSu6odFGKOM6v6ywa8k6JBHgRieCTUTvc5V/Xf4OLhE3Xsw/j6i3u7jeFORbi9NAuTqmKYPI8gtf+kx7CWhkaC+fnuDiEQ+UUJYd8tvA3duziNC1zAnNYJTUwh332R/VZXNjv1xlV8n2KbuZu3xQBLhIDlKtSeTKbVHei8rrFWYBwySLj6euAiE8+BA=" 


script:
- qmake
- make
- "./tests/tests"

after_success:
- coveralls --root . -E ".*external.*" -E ".*tests.*"
- build-wrapper-linux-x86-64 --out-dir bw-output make clean all
- sonar-scanner

cache:
  directories:
  - "$HOME/.sonar/cache"
  
notifications:
  email: false
