language:
- cpp

dist: trusty

before_install:
  - pip install --user cpp-coveralls


addons:
  sonarcloud: 
   organization: "dzigen"
   token:
    secure: "S5Zmy5yyk1tDctO1eIj0A8jVhuToKGcKsLdd7UJ7xhwpTCH76yei7fAweGBZ0/Jt01CpgpG2Ffz01/COuMRply6u9jUSBoATkRknSZCQF3OalGFA79yLmNg/Zzpao0gc+MoxDYwqPHYxKy4C/dKnR+y0T47lRQq7sKqpY0C4qAVPwj8rAlznc+PUYRWmEfi8TBYX3yQ7bOKKY0BjgJYnaLcJNZzGeIS4oVovVrsxDgsG2iuOkQuGazG2wBw8FSazHxbk+AWR6J4VGwYfi9h/5wq8Hf6dxevsBOUMl0X3IB9hMYIvVOVGNXuE3/URryA5+l8zb0NZGWBxNMCd4zksh1Op6/IpYflz7BIUBKbnMieggHY2LtrI9Yncvpd3Mefeyz+PVQynZEW3QJr0i9XAFPN72AVEqUzGmfvwYqII2eNzZ3zKEq6XwpV1wR4Gfxp5YJDsdUlZNTun2hw/SA/2+wlWV/0omuIXWDy8OVhnxeiRZ9Kji6VKEI9n5CAGi7eASoNhps3kG97HFWTFFvyTiPTk3KM6bmeAja38Y66YTp/mSRHAtANxIhRJh9d8tXn5/k1xOzZfVeEqewiE9XIo3OMgYVI35dxu7XcMg/YXyIubFooDZS0C6j+AxnNrlyU4d0N+FA15PLXlq86oFnNm1CmHN1LMEK/1NkycvTuemEg="


script:
- qmake
- make
- "./tests/tests"

after_success:
- coveralls --root . -E ".*external.*" -E ".*tests.*"
- build-wrapper-linux-x86_64 --out-dir bw-output make clean all- sonar-scanner

cache:
  directories:
  - "$HOME/.sonar/cache"
  
notifications:
  email: false
