language:
- cpp

before_install:
  - pip install --user cpp-coveralls

dist: trusty

addons:
<<<<<<< HEAD
  sonarcloud:
    organization: "dzigen"
    token:
      secure: "idUEnFJTUgrZSFwfKYHuHLiTBEVJIFDdF3gtO+fqGNEWwenJtrJxTIKUl5wVzwABL3XPtL7+i50KcVrVfUjIuKGRMJwX564p6l8mvG6rhOg5jcqqkbK5J0TwF8wNvLFhVj3SwBA8gjPnR/4fk2NFJFwAywlSfh7cgh7EyDzyrJcNzogpppHmwRGCBsuGzrIMOSDsEBxwbl/uyxSkGyDBFknquN/xPyNntKvmMIXvwaRQvhlL98GfFKbt+HvRb8CzoJEPRMYLmeL8cjMaqNmH5DiuLsypET+bMK5G0zSj8NHkK53MXLxLX6gp7QylA60jcKAxUNCyRoiJ23yrxOxPO+p6aspgPeq8vqRSFQnGBzuGx7UhPBwafzaKS+LbUkttgkhI6Gl+dOJl/i1z/7MexehVe3LY5W+ttLKdSXFc+WTIPNT2TdkXt7duwpwXY9ayPFggxW/EH6p/0DvlATIdh8Fx9n8j6zksjRu9IWNqTOlriCtWpG137rYERxMs+3WPNUdBeuQiXqEgRom20wgQ7hcaTJrU4F5PxAAOcsRlbCJZzsyAbrqAo5NvPEkKuDpMbut1W6bjSLMEaZVja76LM7FBGcKSRSp80LHtX9gXzTypdbpQeIRHnkKJ/rmyW4j8F1dNrwPQn0kcSH+SFEDysa8LbqCBbxMH6ZrBy1eUJG4="
=======
  sonarcloud: 
  organization: "dzigen"
  token:
   secure: "jWm0ka4KE/Dy6miXkCESmkPaUlDTNkM5fV4qm9upEUhiaZZdFSNNExzp84AcGEaoa3/V9tkhiDtxsouZ8L6f08hZOaGzbPjQ/cQ3VFq4XPpmwtmOleKkrsNmrS8gDmvMMNvDUxyPXiASvLQ3E7bVb/3fnG+Deg65CjrUg3CrGb99uOblND6dzrmEQ0Nintd63yqhEyimO9/HYQTEyOMx6jUvEu+2N9jiKfevyB8RF71r3Qa2m5szdZwOgERyYymQwgmzBKPe/EFh1z1KqjG1HYhXwvZRn1V/PvmSGCXT+zWwr5E1l2P6gLIwfgI13x25KH8KfokLfFGAAQLAzkt6VtZZpNkjprhzv9tlIpqPABCTcmDeYVtFmVsOv+TaImGSCG5q8xtBTkSld2GBiSS1enokm7wFvVl+ClEEkzWZEQDU1FOTJsMAgJ1VM+5RSDyukpArGPK3/dg53CwtjWzFJTY8Gutv/Gi7ysngnAkpJjYP1v7VEvAps5KCM2lnYiU6hJXlujwKsaYwX5XqYHfo4I16PgPC60apAfqMmgRXwhpiCJERfxDPCwjCEV99ntODjlPJQWo4IknZgfBAgSfuXL1pKvRedM528yku58kSyR9QqCrAhzWyTOe5pRaMxoOmJCwQwi+3QEmU5TMj1M5iQ3+d08N0ye3QgQEZPY0JFQg="
>>>>>>> 2c5cf3e7a9a69a9b6ab45c6134467ffafaf11576


script:
- qmake
- make
- "./tests/tests"

after_success:
- coveralls --root . -E ".*external.*" -E ".*tests.*"
- build-wrapper-linux-x86-64 --out-dir bw-output make clean all
- sonar-scanner

cache:
  directories:
  - "$HOME/.sonar/cache"
  
notifications:
  email: false
