language:
  - cpp

before_install:
  - pip install --user cpp-coveralls

addons:
  sonarcloud:
   organization:"dzigen"
   token:
    secure: $7ca78dc27da410a308e9a7e6720db95da37ad196

script:
  - qmake
  - make
  - ./tests/tests

after_success:
  - coveralls --root . -E ".*external.*" -E ".*tests.*"
  - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
  - sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output

cache:
 directories:
  -'$HOME/.sonar/cache'

notifications:
  email: false
